name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # For action testing you can also run this manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |
        mkdir -p build
        date > build/builddate.txt
        # npm install
        # npm run build
        # Fake build step (comment out and uncomment the npm lines)
        echo "hello world" > build/index.html        
        cat build/builddate.txt >> build/index.html
      
    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        ls -la
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        git clone git@github.com:scribear/v.git
        git config --global user.email "angrave@illinois.edu"
        git config --global user.name "scribear-bot"
        cd v
        ls -la
        export SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`
        git rm -r latest
        git-filter-repo --path ./latest --invert-paths
        mkdir -p latest
        mv ../build/* latest
        git add latest

        git commit -m "Commit Deploy: ${SHORT_SHA}"
        git push origin master --force
